spring:
  application.name: inventory-management-system
  data:
    mongodb:
      uri: ${MONGO_URI}/inventory_db
#      uri: mongodb://localhost:27017/inventory_db

logging:
  level:
    org.mongodb.driver: ERROR
